
package com.ichaoge.pet.service.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DigiFlowControl", targetNamespace = "urn:DefaultNamespace")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DigiFlowControl {


    /**
     * 
     * @param opt
     * @return
     *     returns com.wm.oa.domain.rpc.PROCESSSTAT
     */
    @WebMethod(operationName = "CREATEDOCWITHFLOW")
    @WebResult(name = "CREATEDOCWITHFLOWReturn", partName = "CREATEDOCWITHFLOWReturn")
    public PROCESSSTAT createdocwithflow(
            @WebParam(name = "OPT", partName = "OPT")
                    DIGIFLOWPARA opt);

    /**
     * 
     * @param opt
     * @return
     *     returns com.wm.oa.domain.rpc.RETURNINFO
     */
    @WebMethod(operationName = "SUBMITFLOWDOC")
    @WebResult(name = "SUBMITFLOWDOCReturn", partName = "SUBMITFLOWDOCReturn")
    public RETURNINFO submitflowdoc(
            @WebParam(name = "OPT", partName = "OPT")
                    BACKFLOWPARAS opt);

}
