
package com.ichaoge.pet.service.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "DigiFlowControlService", targetNamespace = "urn:DefaultNamespace", wsdlLocation = "http://qa.oa01.wumart.com/flow/flowprocess.nsf/DigiFlowControlService?WSDL")
public class DigiFlowControlService_qa
    extends Service
{
    private final static URL DIGIFLOWCONTROLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DIGIFLOWCONTROLSERVICE_EXCEPTION;
    private final static QName DIGIFLOWCONTROLSERVICE_QNAME = new QName("urn:DefaultNamespace", "DigiFlowControlService");

    static {


        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://qa.oa01.wumart.com/flow/flowprocess.nsf/DigiFlowControlService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DIGIFLOWCONTROLSERVICE_WSDL_LOCATION = url;
        DIGIFLOWCONTROLSERVICE_EXCEPTION = e;
    }

    public DigiFlowControlService_qa() {
        super(__getWsdlLocation(), DIGIFLOWCONTROLSERVICE_QNAME);
    }

    public DigiFlowControlService_qa(WebServiceFeature... features) {
        super(__getWsdlLocation(), DIGIFLOWCONTROLSERVICE_QNAME, features);
    }

    public DigiFlowControlService_qa(URL wsdlLocation) {
        super(wsdlLocation, DIGIFLOWCONTROLSERVICE_QNAME);
    }

    public DigiFlowControlService_qa(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DIGIFLOWCONTROLSERVICE_QNAME, features);
    }

    public DigiFlowControlService_qa(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DigiFlowControlService_qa(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DigiFlowControl
     */
    @WebEndpoint(name = "Domino")
    public DigiFlowControl getDomino() {
        return super.getPort(new QName("urn:DefaultNamespace", "Domino"), DigiFlowControl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DigiFlowControl
     */
    @WebEndpoint(name = "Domino")
    public DigiFlowControl getDomino(WebServiceFeature... features) {
        return super.getPort(new QName("urn:DefaultNamespace", "Domino"), DigiFlowControl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DIGIFLOWCONTROLSERVICE_EXCEPTION!= null) {
            throw DIGIFLOWCONTROLSERVICE_EXCEPTION;
        }
        return DIGIFLOWCONTROLSERVICE_WSDL_LOCATION;
    }

}
